name: snyk-test-changes-from-upstream
on:
  pull_request

jobs:
  test-only-changes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "snyk test automation"
          git config user.email "<>"
          
      - name: setup snyk
        run: |
          # download latest snyk cli and make it executable
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/

      - name: test changes
        run: |
          # make our local executable
          chmod +x "${GITHUB_WORKSPACE}/scripts/snyk_git_diff.sh"
          ${GITHUB_WORKSPACE}/scripts/snyk_git_diff.sh test

